### ISSUE TITLE
碩士班簡章文字確認按鈕之文字為「確認上傳資料並提交」按鍵並非「確認資料」

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#129]

**Comment by x3388638** [comment]
無法重現
![螢幕快照 2017-10-31 下午9.24.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/568c21b2660b4b0e006dc336/125516c66e82c728ace21e0d46606a58a65b762c502238a6631da2c478116a227949f07a30013bc33aaf9358415d4ab2405b4d58eeb9cb74fce36f34985619e8d8695f25c63c19aebf8317eb09ba20d81a82e7b58d4ec0fa2137a5dad11b61435c52dcbd4f3fb29843c259f34be84950a2113165ee703e6e0a.png)
