### ISSUE TITLE
提交備審資料後的信件內容

### ISSUE THREAD

**Issue by hewen-lotus** [0verseas/0verAPI#156]
1 信件主旨更改為 海外聯合招生委員會--志願校系審查資料上傳確認信
2 信件內容  原"您已確認完成上傳備審資料 上傳狀態如下"  更改為 "您已於?年?月?日?時間(IP位址)確認完成「海外聯合招生委員會--志願校系審查資料」上傳作業，上傳資料清冊如下："
3 清單比照就報名系統

**Comment by sunnyworm** [comment]
清單比照舊報名系統，
這邊沒有資料哦，
上傳系統的 code 我一行都沒有看過。
