### ISSUE TITLE
簡章系統＿總量檢查

### ISSUE THREAD

**Issue by hewen-lotus** [0verseas/0verAPI#183]
各系系所分則頁面中填報名額需檢查不能超過總量

**Comment by zxp86021** [comment]
哪部份的名額？總量是看哪裡？

**Comment by hewen-lotus** [comment]
好像是說 在系所資料裡面個系也可以去更改招收名額
但是在名額分配有檢查總量，但在系所資料裡面沒有檢查

**Comment by zxp86021** [comment]
fix at https://github.com/0verseas/0verAPI/commit/aed4edaa436e1a0ba16656c340e26f369747e5c9

**Comment by zxp86021** [comment]
名額統一移到名額分配頁面處理
