### ISSUE TITLE
[簡章調查] 儲存時不檢查必填欄位是否有填

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#24]

**Comment by passerbyid** [comment]
這樣是要全部欄位改成 nullable，還是怎樣？

**Comment by zxp86021** [comment]
DB: 不用，因為 NULL 代表的是沒有這東西，但是我們是有東西但是是空的

Input validate: 要，因為要允許空值可以過驗證

**Comment by sunnyworm** [comment]
不用改成nullable, 填空字串不是嗎

**Comment by sunnyworm** [comment]
噢謝謝蛋蛋

**Comment by zxp86021** [comment]
空字串 != NULL

**Comment by passerbyid** [comment]
懂了，看來我昨天改 DB 是不該的 QQ。

**Comment by DevanshBajaj** [comment]
@zxp86021 Make website y'all

**Comment by DevanshBajaj** [comment]
@zxp86021 Take template from me and delete images(home screens) 😂😂
