### ISSUE TITLE
[簡章調查] 取得審查項目分類資料 API

### ISSUE THREAD

**Issue by passerbyid** [0verseas/0verAPI#31]
```
GET /systems/{system_id}/application-document-types
```

#### Parameters

none

#### Responsive

A ApplicationDocumentType object array.

**Comment by locxFIN** [comment]
@passerbyid Theme wise?

**Comment by passerbyid** [comment]
@zxp86021 寫好了
5198b54bb31f1c803af298eb1df63dd10a9eb66b
