### ISSUE TITLE
[簡章調查] 更新編輯資料成功後，call 任一 API 皆會噴錯

### ISSUE THREAD

**Issue by passerbyid** [0verseas/0verAPI#35]
error 400

`{
	"messages": [
		"Sorry, something went wrong."
	],
	"exception": "Illuminate\\Auth\\AuthenticationException",
	"message": "Unauthenticated.",
	"trace": [
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/AuthenticateSession.php",
			"line": 51,
			"function": "logout",
			"class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Middleware\/Authenticate.php",
			"line": 43,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Auth\\Middleware\\Authenticate",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php",
			"line": 64,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Session\\Middleware\\StartSession",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/AddQueuedCookiesToResponse.php",
			"line": 37,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php",
			"line": 59,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 102,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
			"line": 576,
			"function": "then",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
			"line": 535,
			"function": "runRouteWithinStack",
			"class": "Illuminate\\Routing\\Router",
			"type": "->",
			"args": [
				{
					"uri": "schools\/{school}\/histories\/{history}",
					"methods": [
						"GET",
						"HEAD"
					],
					"action": {
						"middleware": "web",
						"as": "schools.histories.show",
						"uses": "App\\Http\\Controllers\\SchoolHistoryDataController@show",
						"controller": "App\\Http\\Controllers\\SchoolHistoryDataController@show",
						"namespace": "App\\Http\\Controllers",
						"prefix": "\/",
						"where": []
					},
					"controller": {},
					"defaults": [],
					"wheres": [],
					"parameters": {
						"school": "me",
						"history": "latest"
					},
					"parameterNames": [
						"school",
						"history"
					],
					"computedMiddleware": [
						"web",
						"auth",
						"switch"
					],
					"compiled": {}
				},
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
			"line": 513,
			"function": "dispatchToRoute",
			"class": "Illuminate\\Routing\\Router",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
			"line": 174,
			"function": "dispatch",
			"class": "Illuminate\\Routing\\Router",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 30,
			"function": "Illuminate\\Foundation\\Http\\{closure}",
			"class": "Illuminate\\Foundation\\Http\\Kernel",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php",
			"line": 30,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php",
			"line": 30,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php",
			"line": 27,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/barryvdh\/laravel-cors\/src\/HandleCors.php",
			"line": 36,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "Barryvdh\\Cors\\HandleCors",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/app\/Http\/Middleware\/CheckForMaintenanceMode.php",
			"line": 43,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 148,
			"function": "handle",
			"class": "App\\Http\\Middleware\\CheckForMaintenanceMode",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				},
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php",
			"line": 53,
			"function": "Illuminate\\Pipeline\\{closure}",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
			"line": 102,
			"function": "Illuminate\\Routing\\{closure}",
			"class": "Illuminate\\Routing\\Pipeline",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
			"line": 149,
			"function": "then",
			"class": "Illuminate\\Pipeline\\Pipeline",
			"type": "->",
			"args": [
				{}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
			"line": 116,
			"function": "sendRequestThroughRouter",
			"class": "Illuminate\\Foundation\\Http\\Kernel",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/public\/index.php",
			"line": 53,
			"function": "handle",
			"class": "Illuminate\\Foundation\\Http\\Kernel",
			"type": "->",
			"args": [
				{
					"attributes": {},
					"request": {},
					"query": {},
					"server": {},
					"files": {},
					"cookies": {},
					"headers": {}
				}
			]
		},
		{
			"file": "\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/server.php",
			"line": 21,
			"args": [
				"\/Users\/Yuer\/Projects\/Overseas\/0verAPI\/public\/index.php"
			],
			"function": "require_once"
		}
	]
}`

**Comment by zxp86021** [comment]
maybe fix at  https://github.com/0verseas/0verAPI/commit/30fc31589c10a20633a0efaea12a12b62743e9c2
