### ISSUE TITLE
exception handler 回錯東西了啦

### ISSUE THREAD

**Issue by passerbyid** [0verseas/0verAPI#36]
我也不知道什麼情況， @zxp86021 說的。

**Comment by zxp86021** [comment]
不是齁，是 exception handler 回錯東西而已，auth middleware 是好的

**Comment by passerbyid** [comment]
所以我說，我不知道 XD

**Comment by zxp86021** [comment]
fix 
https://github.com/0verseas/0verAPI/commit/65abb99756b8552c6e06e16a6acb493b6be31d14

**Comment by pagaiba** [comment]
@passerbyid :(
