### ISSUE TITLE
[簡章調查] 學校頁面按下儲存後偶爾會有 400 Bad Request

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#39]
sunnyworm commented a day ago collaborator

按儲存後前端顯示儲存成功，
不過 API 是回 400 Bad Request

messages
0 "Sorry, something went wrong."
exception "BadMethodCallException"
message "Method [index] does not exist."

Response { type: "cors", url: "https://api.overseas.ncnu.edu.tw/sc…", redirected: false, status: 400, ok: false, statusText: "Bad Request", headers: Headers, bodyUsed: false } schoolInfo.js:160:6
zxp86021 commented 6 hours ago collaborator

400 是因為前端想 GET /schools/01/histories/ 但是我們並沒有寫這個功能

**Comment by sunnyworm** [comment]
使用臺科大帳號在線上機器測試
name: 國立臺灣科技大學, username: ntust, password: %eVLk^B7%euQE+C
中文網址留白，輸入英文網址時會回應 400 
messages "The approval no of self enrol…en has self enrollment is 1."

**Comment by zxp86021** [comment]
看了一下發現在中文網址留白，輸入英文網址時，approval_no_of_self_enrollment 這欄會是空值

這是正常狀況：
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="address"

10607台北市大安區基隆路四段43號
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="eng_address"

43,Sec.4,Keelung Rd.,Daan District, Taipei,106,Taiwan,R.O.C.NULL
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="organization"

承辦單位中文名稱
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="eng_organization"

eng_organization
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="url"

http://www.ntust.edu.tw
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="eng_url"

http://www.ntust.edu.tw
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="phone"

886-2-27301190
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="fax"

886-2-27376661
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="has_dorm"

1
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="has_scholarship"

0
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="has_five_year_student_allowed"

1
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="has_self_enrollment"

1
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="dorm_info"

新生優先分配住宿
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="eng_dorm_info"

eng_dorm_info
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="rule_of_five_year_student"

第22條
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="rule_doc_of_five_year_student"

undefined
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="approval_no_of_self_enrollment"

http://www.ntust.edu.tw
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="approval_doc_of_self_enrollment"

undefined
-----------------------------18563714644154600501943815701
Content-Disposition: form-data; name="action"

save
-----------------------------18563714644154600501943815701--


這是壞掉的狀況：
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="address"

10607台北市大安區基隆路四段43號
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="eng_address"

43,Sec.4,Keelung Rd.,Daan District, Taipei,106,Taiwan,R.O.C.NULL
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="organization"

承辦單位中文名稱
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="eng_organization"

eng_organization
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="url"


-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="eng_url"

http://www.ntust.edu.tw
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="phone"

886-2-27301190
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="fax"

886-2-27376661
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="has_dorm"

1
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="has_scholarship"

0
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="has_five_year_student_allowed"

1
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="has_self_enrollment"

1
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="dorm_info"

新生優先分配住宿
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="eng_dorm_info"

eng_dorm_info
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="rule_of_five_year_student"

第22條
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="rule_doc_of_five_year_student"

undefined
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="approval_no_of_self_enrollment"


-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="approval_doc_of_self_enrollment"

undefined
-----------------------------14631605541435659189629050424
Content-Disposition: form-data; name="action"

save
-----------------------------14631605541435659189629050424--

使用同一頁靣，僅刪除中文網址

**Comment by sunnyworm** [comment]
不過照理說沒有輸入中文網址應該是不會往下執行
因為這邊並不是 nullable?
'scholarship_url' => 'required_if:has_scholarship,1|url', //僑生專屬獎學金說明網址

**Comment by sunnyworm** [comment]
看錯行了，有改成 present
https://github.com/0verseas/0verAPI/blob/master/app/Http/Controllers/SchoolHistoryDataController.php#L122

**Comment by zxp86021** [comment]
噴

**Comment by passerbyid** [comment]
需要重現錯誤

**Comment by zxp86021** [comment]
這個可能要請前端看一下，因為我看到的是前端送出來的資料不一樣

**Comment by lemon5920** [comment]
請問是前端這裡把空的中文 url 送出去了嗎？
是的話我再檢查儲存時的表單驗證。

**Comment by zxp86021** [comment]
@lemon5920 請看我上面的回應

**Comment by lemon5920** [comment]
我發現錯誤了，抱歉，是前端這裡包錯，
@sunnyworm 請問我要改在 master 還是 refactor?

**Comment by passerbyid** [comment]
這還有發生嗎？

**Comment by zxp86021** [comment]
@sunnyworm 這個可以 close 了（？

**Comment by sunnyworm** [comment]
看起來都沒有發生了
