### ISSUE TITLE
[簡章調查] 學校不喜歡複雜的密碼

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#46]
他們想要123456就好，
要改一個不 commit 上去的 Seeder

**Comment by zxp86021** [comment]
你全家都不喜歡！

**Comment by sunnyworm** [comment]
只好 commit 他們喜歡的密碼上去了

**Comment by zxp86021** [comment]
使用新版密碼產生方式
https://github.com/0verseas/0verAPI/commit/5410d89e4d2d73b6c5cffd3d2f705e2eaf11a4b9
