### ISSUE TITLE
[簡章調查] 獎學金資訊的英文欄位不需要必填

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#47]

**Comment by zxp86021** [comment]
已設定 nullable，要看一下前端包了什麼東西過來

**Comment by sunnyworm** [comment]
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="has_dorm"

1
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="has_scholarship"

1
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="has_five_year_student_allowed"

1
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="has_self_enrollment"

1
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="dorm_info"

新生保障住宿
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="eng_dorm_info"

ha
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="scholarship_dept"

test
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="eng_scholarship_dept"


-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="scholarship_url"

https://geg.dc
-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="eng_scholarship_url"


-----------------------------20959335736579405531577952014
Content-Disposition: form-data; name="rule_of_five_year_student"

第17條

**Comment by passerbyid** [comment]
是前端問題，已修復在 https://github.com/0verseas/0verSchool/commit/8f5e884d15bfef6de9eea369df28778fe74db427

**Comment by passerbyid** [comment]
API 部分，系所資料跟學校資料，都有英文欄位驗證問題：若是空資料，會不讓過。

**Comment by sunnyworm** [comment]
這邊是要改成 present ，還是還有其他問題呢？

**Comment by zxp86021** [comment]
最簡單的作法就是把 required_if 改成 present

**Comment by passerbyid** [comment]
蛋蛋好像修掉了 d6b20b8d6a27ffbb4cdc968ad715b12b4644f323
