### ISSUE TITLE
[API] PATCH /schools/01/editors/test01

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#5]
修改臺大的 test01 編輯之資訊

**Comment by sunnyworm** [comment]
帳號不能修改（應為正常），
password, email, name, eng_name, phone, organization 修改成功，
has_banned 只設定 editor 權限，不影響 user 權限，
banned 之後要怎麼再開啟，清空 deleted_at 嗎 XD

**Comment by sunnyworm** [comment]
自己不能 ban 自己（正常）

**Comment by zxp86021** [comment]
"banned 之後要怎麼再開啟，清空 deleted_at 嗎" -> 對，但是忘記有沒有做解鎖了

**Comment by sunnyworm** [comment]
沒關係先放著，應該很少用到，大不了開DB manager  起來處理

**Comment by zxp86021** [comment]
剛剛看了 code，沒做
