### ISSUE TITLE
[API] POST /schools/01/histories/ 測試, action: save

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#7]

**Comment by sunnyworm** [comment]
已經有中五學則的學校就不需要再上傳學則，自招也是。

這個部份目前看起來會要求已經有中五學則的學校上傳檔案。
我們需要區分「已經有中五學則」的學校與「還沒有中五學則」的學校。

**Comment by zxp86021** [comment]
所以這裡要多開一張表紀錄去年的自招跟中五招生狀況？

**Comment by sunnyworm** [comment]
是

**Comment by zxp86021** [comment]
https://github.com/0verseas/0verAPI/commit/3cfdfe3766d45b8b273f50a15c49edd1c4fac626
開表

**Comment by zxp86021** [comment]
maybe fix at https://github.com/0verseas/0verAPI/commit/2b31ef35a4a874166bb165daec29137a180cfafc

**Comment by sunnyworm** [comment]
按儲存後前端顯示儲存成功，
不過 API 是回 400 Bad Request

messages	
0	"Sorry, something went wrong."
exception	"BadMethodCallException"
message	"Method [index] does not exist."

Response { type: "cors", url: "https://api.overseas.ncnu.edu.tw/sc…", redirected: false, status: 400, ok: false, statusText: "Bad Request", headers: Headers, bodyUsed: false }  schoolInfo.js:160:6

**Comment by zxp86021** [comment]
400 是因為前端想 GET /schools/01/histories/ 但是我們並沒有寫這個功能

**Comment by zxp86021** [comment]
不過這應該要回 404 才對
已更新 https://github.com/0verseas/0verAPI/commit/88cf32034533e5b954cce5a28a43d56843341815

**Comment by sunnyworm** [comment]
另開 issue 追蹤 #39
