### ISSUE TITLE
[簡章調查] 什麼情況下 history_id 會變成 null

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#74]
看 log 看到的，沒有接到什麼通知

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'history_id' cannot be null (SQL: insert into `two_year_tech_dept_history_application_docs` (`history_id`, `dept_id`, `type_id`, `description`, `eng_description`, `required`, `modifiable`, `updated_at`, `created_at`) values (, 89001, 19, 請輸入詳細說明，如份數與類型(畢業證書/修業證明/離校證明/在學證明)等, 請輸入英文詳細說明，如份數與類型(畢業證書/修業證明/離校證明/在學證明)等, 1, 0, 2017-07-28T11:31:21+0800, 2017-07-28T11:31:21+0800)) in /var/www/0verAPI/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

**Comment by zxp86021** [comment]
二技系所歷史資料新增失敗的時候

**Comment by zxp86021** [comment]
問題解決，有人把 ORM 的 autoincrement 關掉了

**Comment by zxp86021** [comment]
然後我把所有的 DB transaction 先拿掉了
