### ISSUE TITLE
[簡章調查] 增加備審資料中英說明長度至1000字元以上

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#75]
Next Illuminate\Database\QueryException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'description' at row 1 (SQL: insert into `dept_history_application_docs` (`history_id`, `dept_id`, `type_id`, `description`, `eng_description`, `required`, `modifiable`, `updated_at`, `created_at`) values (3201, 13403, 12, 審查費NTD$600元(或USD$25元)(不含手續費)請上傳匯款收據正本。國內繳費：第一商業銀行板橋分行，戶名：國立臺灣藝術大學-招生考試報名408專戶，帳號：20130066833。國外繳費Beneficiary：National Taiwan University of Arts, Beneficiary Account Number：20130066833 Beneficiary with Bank：First Commercial Bank, Taipei, Taiwan, Beneficiary Bank Address Address: No.107, Sec.1, Si-Chuan Road, Banqiao Dist., New Taipei City 220,   Taiwan(R.O.C.) Swift Code：FCBKTWTP審查費一經繳交，概不退還，未於報名期限內完成審查費繳交者，視同審查資格不符。請匯完審查費款項後，1-2天內將匯款收據正本電子檔Email至aaca@ntua.edu.tw信箱，並註明報考人中英文姓名及報考學系，始完成報名手續。, , 1, 1, 2017-07-28T11:30:21+0800, 2017-07-28T11:30:21+0800)) in /var/www/0verAPI/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

**Comment by sunnyworm** [comment]
備審資料說明欄位一直噴不夠長的錯誤，可是沒什麼人打電話進來 ._.

**Comment by sunnyworm** [comment]
改為將所有的 description 都設定為 longText

**Comment by zxp86021** [comment]
add at https://github.com/0verseas/0verAPI/commit/da3f81154ecd28a4ae69183873ed72cf857ca9a5

**Comment by zxp86021** [comment]
https://github.com/0verseas/0verSchool/issues/53
