### ISSUE TITLE
港二技系所資料不傳檔案時會有錯

### ISSUE THREAD

**Issue by passerbyid** [0verseas/0verAPI#76]
不傳檔案時 `approval_doc_of_special_class` 會是 `undefined `，API 會驗證不過：「"The approval doc of special class must be a file」

**Comment by passerbyid** [comment]
在學校資料頁的檔案是直接不用 Validator 檢查

**Comment by zxp86021** [comment]
請前端修正沒帶檔案給個空白就好

**Comment by lemon5920** [comment]
Fixed [800540a](https://github.com/0verseas/0verSchool/commit/800540a3b0ceec019b793db45fb6865398cef7d4)
沒有上傳檔案是帶 空字串
