### ISSUE TITLE
[簡章調查] 個人申請人數為 0 時 PDF 不印出備審資料

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#77]

**Comment by zxp86021** [comment]
你是指這樣？
https://github.com/0verseas/0verAPI/commit/d2af364100e05d5357871f436066b47e2aa0d279

**Comment by sunnyworm** [comment]
有聯合分發名額時只有「備審資料」不印出，其他資料如系名、名額都還是需要

**Comment by zxp86021** [comment]
原來如此

**Comment by zxp86021** [comment]
https://github.com/0verseas/0verAPI/commit/6bb06226cb790754d07923d1b907074f44da8e6a
