### ISSUE TITLE
[API] GET /schools/01/systems/1/histories/latest?data_type=info 測試

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#8]

**Comment by sunnyworm** [comment]
學士班 ok,
二技 404 (臺大沒有二技)
碩士班 ok,
博士班 ok

**Comment by passerbyid** [comment]
只是剛好台大沒有的是二技，所以應該各學制頁面都還沒處理 404？

**Comment by passerbyid** [comment]
好，我忘記這邊只處理 API 了（敲頭

**Comment by sunnyworm** [comment]
http://localhost:8000/schools/01/systems/1/histories/latest?data_type=info

回來的系所資料裡面，系所 id 需要是 string

**Comment by sunnyworm** [comment]
83c455d
修好了
