### ISSUE TITLE
[簡章調查] user 的 last_login_at 與 school_editor 的 last_action_at 看起來沒有在紀錄

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#82]
確認一下這邊後來有沒有要做

**Comment by zxp86021** [comment]
@sunnyworm 那時候好像是說先放著

**Comment by sunnyworm** [comment]
ok 瞭解

**Comment by zxp86021** [comment]
或是現在要加也可以，要改很快

**Comment by zxp86021** [comment]
@sunnyworm 願望幫你實現了
https://github.com/0verseas/0verAPI/commit/be52637c85d2b0e408a0788e59f573d8d95bfce9
https://github.com/0verseas/0verAPI/commit/fcf4e773aef9b814b7f439fc9a931780d76e36a7
