### ISSUE TITLE
變更身份別的時候要清空相關資料

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verAPI#95]
除了判斷學制變更以外、身份別變更（港澳換海外僑生）也要判斷。
需要清空個人基本資料內的僑居地資料與學歷相關欄位、
入學資料、
奧林匹亞志願、
個人申請志願、
聯合分發成績採計方式、
聯合分發志願。

**Comment by zxp86021** [comment]
add @ https://github.com/0verseas/0verAPI/commit/9c8c5872ffdcd4809278586c1c0da36805c509b8
